apiVersion: application.margo.org/v1alpha1
kind: ApplicationDeployment
metadata:
  annotations:
    id: d3b49c6d-d5a5-4685-9a94-a5bd91bfcaa0
    applicationId: com-schneider-electric-hello-world
  name: com-schneider-electric-hello-world-deployment
  namespace: margo
spec:
    deploymentProfile:
        type: docker-compose
        components:
            - name: hello-world-1
              properties:
                packageLocation: https://raw.githubusercontent.com/SE-I-T-Digital/hello-world-color/c5ccfacb7af5f3a6a0964c032af2acf1c6ec74c2/docker-compose.yml
                revision: 0.1.1
            - name: hello-world-2
              properties:
                packageLocation: https://raw.githubusercontent.com/SE-I-T-Digital/hello-world-color/c5ccfacb7af5f3a6a0964c032af2acf1c6ec74c2/docker-compose.yml
                revision: 0.1.1
            - name: hello-world-3
              properties:
                packageLocation: https://raw.githubusercontent.com/SE-I-T-Digital/hello-world-color/c5ccfacb7af5f3a6a0964c032af2acf1c6ec74c2/docker-compose.yml
                revision: 0.1.1
    parameters:
        backgroundColor1:
            value: lightcoral
            targets:
                - pointer: BACKGROUND_COLOR
                  components:
                    - hello-world-1
        backgroundColor2:
            value: lightgreen
            targets:
                - pointer: BACKGROUND_COLOR
                  components:
                    - hello-world-2
        backgroundColor:
            value: lightblue
            targets:
                - pointer: BACKGROUND_COLOR
                  components:
                    - hello-world-3
        displayImage1:
            value: hello-world.png
            targets:
                - pointer: DISPLAY_IMAGE
                  components:
                    - hello-world-1
        displayImage2:
            value: hello-world-2.png
            targets:
                - pointer: DISPLAY_IMAGE
                  components:
                    - hello-world-2
        displayImage:
            value: hello.png
            targets:
                - pointer: DISPLAY_IMAGE
                  components:
                    - hello-world-3
        srcImage:
            value: hello.png
            targets:
                - pointer: ==FILE==
                  components:
                    - hello-world-3
        hostPort1:
            value: 8080
            targets:
                - pointer: HOST_PORT
                  components:
                    - hello-world-1
        hostPort2:
            value: 8081
            targets:
                - pointer: HOST_PORT
                  components:
                    - hello-world-2
        hostPort:
            value: 8082
            targets:
                - pointer: HOST_PORT
                  components:
                    - hello-world-3
